# Generated by Django 4.2.10 on 2026-06-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscategory',
            options={},
        ),
        migrations.AddField(
            model_name='newscategory',
            name='default_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='تصویر پیش\u200cفرض دسته'),
        ),
    ]
