# Generated by Django 4.2.10 on 2026-06-21 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='diagnosis/%Y/%m/', verbose_name='تصویر MRI')),
                ('result', models.CharField(choices=[('CN', 'سالم'), ('MCI', 'اختلال خفیف شناختی'), ('AD', 'آلزایمر'), ('PENDING', 'در حال بررسی')], default='PENDING', max_length=10, verbose_name='نتیجه')),
                ('confidence', models.FloatField(blank=True, null=True, verbose_name='درصد اطمینان')),
                ('heatmap', models.ImageField(blank=True, null=True, upload_to='heatmaps/%Y/%m/', verbose_name='نقشه حرارتی')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات پزشک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پردازش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تشخیص',
                'verbose_name_plural': 'تشخیص\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
