"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qei#k9$kw=x_v=om2unz=)lahk)!_aj$7kmg8egti1zc_20fg%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
     "unfold",  # before django.contrib.admin
    # "unfold.contrib.filters",  # optional, if special filters are needed
    # "unfold.contrib.forms",  # optional, if special form elements are needed
    # "unfold.contrib.inlines",  # optional, if special inlines are needed
    # "unfold.contrib.import_export",  # optional, if django-import-export package is used
    # "unfold.contrib.guardian",  # optional, if django-guardian package is used
    # "unfold.contrib.simple_history",  # optional, if django-simple-history package is used
    # "unfold.contrib.location_field",  # optional, if django-location-field package is used
    # "unfold.contrib.constance",  # optional, if django-constance package is used
    "django.contrib.admin",  # required
    'django.contrib.auth',
    'jalali_date', 

    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    'apps.accounts',
    'apps.news',
    'apps.common',
    'apps.diagnosis',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
#AUTH_USER_MODEL = 'accounts.User'

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
from django.utils.translation import gettext_lazy as _

LANGUAGES = [
    ('fa', _('Persian')),
]
# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'fa-ir'
TIME_ZONE = 'Asia/Tehran'

USE_I18N = True
USE_L10N = True
USE_TZ = True

STATIC_URL = '/static/'
DEBUG = True


STATICFILES_DIRS = [
    BASE_DIR / "static",
]

#STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DEMO_MODE = True

LOGIN_URL = '/signin/'

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}
UNFOLD = {
    "SITE_TITLE": "پنل مدیریت | آفاق‌سازان",
    "SITE_HEADER": "سامانه هوشمند تشخیص آلزایمر",
    "SITE_URL": "/",
    "SITE_LOGO": lambda request: "/static/images/logo-color.png",
    "SITE_LOGO_DARK": lambda request: "/static/images/logo-color.png",
    "SITE_ICON": lambda request: "/static/images/logo-icon-blue.png",
    "SITE_FAVICON": lambda request: "/static/images/logo-icon-blue.png",
    "SITE_SYMBOL": "psychology",

    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SHOW_LANGUAGES": False,
    "SHOW_BACK_BUTTON": False,
    "DASHBOARD_CALLBACK": "core.callbacks.dashboard_callback",

    "STYLES": ["/static/css/admin_custom.css"],
    "SCRIPTS": [],

    "COLORS": {
        "font": {
            "subtle-light": "107 114 128",
            "subtle-dark": "156 163 175",
            "default-light": "75 85 99",
            "default-dark": "209 213 219",
            "important-light": "17 24 39",
            "important-dark": "243 244 246",
        },
        "primary": {
            "50": "240 249 255",
            "100": "224 242 254",
            "200": "186 230 253",
            "300": "125 211 252",
            "400": "56 189 248",
            "500": "14 165 233",
            "600": "2 132 199",
            "700": "3 105 161",
            "800": "7 89 133",
            "900": "12 74 110",
            "950": "8 47 73",
        },
    },

    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "مدیریت کاربران",
                "separator": False,
                "collapsible": False,
                "items": [
                    {
                        "title": "کاربران",
                        "icon": "person",
                        "link": "/admin/auth/user/",
                        "permission": lambda request: request.user.is_superuser,
                    },
                ],
            },
            {
                "title": "تشخیص‌ها",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "تاریخچه تشخیص‌ها",
                        "icon": "biotech",
                        "link": "/admin/diagnosis/diagnosisrecord/",
                    },
                ],
            },
            {
                "title": "محتوای سایت",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "مقالات",
                        "icon": "article",
                        "link": "/admin/news/newsarticle/",
                    },
                    {
                        "title": "دسته‌بندی‌ها",
                        "icon": "category",
                        "link": "/admin/news/newscategory/",
                    },
                    {
                        "title": "نظرات",
                        "icon": "comment",
                        "link": "/admin/news/newscomment/",
                    },
                ],
            },
        ],
    },

    "SITE_DROPDOWN": [
        {
            "icon": "home",
            "title": "صفحه اصلی سایت",
            "link": "/",
            "attrs": {"target": "_blank"},
        },
        {
            "icon": "dashboard",
            "title": "پنل کاربری",
            "link": "/dashboard/",
        },
    ],

    "LOGIN": {
        "image": None,
    },

    "FOOTER": {
        "links": [
            {"link": "/", "label": "سایت اصلی"},
            {"link": "mailto:support@afaqsazan.ir", "label": "پشتیبانی"},
        ],
    },
}
from decouple import config

# قاصدک

GHASEDAK_API_KEY = config('GHASEDAK_API_KEY', default='')
GHASEDAK_TEMPLATE_NAME = config('GHASEDAK_TEMPLATE_NAME', default='Ghasedak')
GHASEDAK_LINE_NUMBER = config('GHASEDAK_LINE_NUMBER', default='3000505')


# تنظیمات تاریخ شمسی
JALALI_DATE_DEFAULTS = {
    'Strftime': {
        'date': '%Y/%m/%d',
        'datetime': '%H:%M:%S _ %Y/%m/%d',
    },
    'Static': {
        'js': [
            'admin/js/django_jalali.min.js',
        ],
        'css': {
            'all': [
                'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css',
            ]
        }
    },
}
# Celery settings (فعلاً کامنت، بعداً فعال کن)
# CELERY_BROKER_URL = 'redis://localhost:6379'
# CELERY_RESULT_BACKEND = 'redis://localhost:6379'