"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qei#k9$kw=x_v=om2unz=)lahk)!_aj$7kmg8egti1zc_20fg%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
     "unfold",  # before django.contrib.admin
    # "unfold.contrib.filters",  # optional, if special filters are needed
    # "unfold.contrib.forms",  # optional, if special form elements are needed
    # "unfold.contrib.inlines",  # optional, if special inlines are needed
    # "unfold.contrib.import_export",  # optional, if django-import-export package is used
    # "unfold.contrib.guardian",  # optional, if django-guardian package is used
    # "unfold.contrib.simple_history",  # optional, if django-simple-history package is used
    # "unfold.contrib.location_field",  # optional, if django-location-field package is used
    # "unfold.contrib.constance",  # optional, if django-constance package is used
    "django.contrib.admin",  # required
    'django.contrib.auth',
    'jalali_date', 

    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    'apps.accounts',
    'apps.news',
    'apps.common',
    'apps.diagnosis',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
#AUTH_USER_MODEL = 'accounts.User'

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
from django.utils.translation import gettext_lazy as _

LANGUAGES = [
    ('fa', _('Persian')),
]
# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'fa-ir'
TIME_ZONE = 'Asia/Tehran'

USE_I18N = True
USE_L10N = True
USE_TZ = True

STATIC_URL = '/static/'
DEBUG = True


STATICFILES_DIRS = [
    BASE_DIR / "static",
]

#STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}
UNFOLD = {
"SITE_DROPDOWN": [
      {
            "icon": "dashboard",
            "title": "داشبورد",
            "link": "/admin/",
        },
        {
            "icon": "public",
            "title": "مشاهده سایت",
            "link": "/",
            "attrs": {"target": "_self"},
        },
      
    ],
    "SITE_TITLE": "پنل مدیریت آلزایمر",

    "SITE_HEADER": "مرکز تشخیص و اطلاع‌رسانی آلزایمر",

    "SITE_URL": "/",

    "SITE_ICON": None,

    "SITE_FAVICON": None,

    "STYLES": [
           "/static/css/custom.css"
        ],

  

    # تصویر پس‌زمینه صفحه ورود (اختیاری)

    "LOGIN": {

        "image": None,  # میتونی یه عکس بذاری

    },

    

    # لوگوی سایت (اختیاری)

    "SITE_LOGO": None,

    

    # فوتر (پایین صفحه)

    "FOOTER": {

        "links": {

            "website": "https://alzheimer.ir",

            "support": "mailto:support@alzheimer.ir",

        },

    },

}
from decouple import config

# قاصدک

GHASEDAK_API_KEY = config('GHASEDAK_API_KEY', default='')
GHASEDAK_TEMPLATE_NAME = config('GHASEDAK_TEMPLATE_NAME', default='Ghasedak')
GHASEDAK_LINE_NUMBER = config('GHASEDAK_LINE_NUMBER', default='3000505')


# تنظیمات تاریخ شمسی
JALALI_DATE_DEFAULTS = {
    'Strftime': {
        'date': '%Y/%m/%d',
        'datetime': '%H:%M:%S _ %Y/%m/%d',
    },
    'Static': {
        'js': [
            'admin/js/django_jalali.min.js',
        ],
        'css': {
            'all': [
                'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css',
            ]
        }
    },
}
# Celery settings (فعلاً کامنت، بعداً فعال کن)
# CELERY_BROKER_URL = 'redis://localhost:6379'
# CELERY_RESULT_BACKEND = 'redis://localhost:6379'